// GET JOB_SUMMARY
export const GET_JOB_SUMMARY = "GET_JOB_SUMMARY"
export const GET_JOB_SUMMARY_SUCCESS = "GET_JOB_SUMMARY_SUCCESS"
export const GET_JOB_SUMMARY_FAIL = "GET_JOB_SUMMARY_FAIL"

// ADD JOB
export const ADD_JOB = "ADD_JOB"
export const ADD_JOB_SUCCESS = "ADD_JOB_SUCCESS"
export const ADD_JOB_FAIL = "ADD_JOB_FAIL"
